# Generated by Django 6.0.5 on 2026-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('pain_points', models.TextField(blank=True)),
                ('team_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enriched', 'Enriched'), ('generated', 'Report Generated'), ('sent', 'Email Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('report_path', models.CharField(blank=True, max_length=500)),
                ('drive_url', models.URLField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
